name: CI/CD Pipeline

on:
  push:
    branches:
      - main        # This workflow will only run on pushes to the 'devel' branch
  pull_request:
    branches:
      - main        # This workflow will only run on pull requests targeting the 'devel' branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java and SBT
        uses: coursier/setup-action@v1 # Installs Java and sbt
        with:
          jvm: 'temurin:25'

      - name: Run topDown
        run: sbt "dynamicProgramming/runMain org.combinators.main.GlossaryToDiskMain topDown"

      - name: Validate topDown
        run: sbt test
        working-directory: ./target/topDown

      - name: Run topDownWithMemo
        run: sbt "dynamicProgramming/runMain org.combinators.main.GlossaryToDiskMain topDownMemo"

      - name: Validate topDownWithMemo
        run: sbt test
        working-directory: ./target/topDownMemo

      - name: Run bottomUp
        run: sbt "dynamicProgramming/runMain org.combinators.main.GlossaryToDiskMain bottomUp"

      - name: Validate bottomUp
        run: sbt test
        working-directory: ./target/bottomUp
