name: CI/CD Pipeline

on:
  push:
    branches:
      - main        # This workflow will only run on pushes to the 'devel' or 'main' branch
      - devel
  pull_request:
    branches:
      - main        # This workflow will only run on pull requests targeting the 'devel' or 'main' branch
      - devel

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java and SBT
        uses: coursier/setup-action@v1 # Installs Java and sbt
        with:
          distribution: temurin
          java-version: 25
          cache: sbt

      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1

      - name: Run Java topDown
        run: sbt "dynamicProgramming/runMain org.combinators.main.GlossaryToDiskMain topDown"

      - name: Validate Java topDown
        run: sbt test
        working-directory: ./target/topDown

      - name: Run Java topDownWithMemo
        run: sbt "dynamicProgramming/runMain org.combinators.main.GlossaryToDiskMain topDownMemo"

      - name: Validate Java topDownWithMemo
        run: sbt test
        working-directory: ./target/topDownMemo

      - name: Run Java bottomUp
        run: sbt "dynamicProgramming/runMain org.combinators.main.GlossaryToDiskMain bottomUp"

      - name: Validate Java bottomUp
        run: sbt test
        working-directory: ./target/bottomUp

      - name: Run topDown
        run: sbt "dynamicProgramming/runMain org.combinators.main.GlossaryScalaToDiskMain topDown"

      - name: Validate Scala topDown
        run: sbt test
        working-directory: ./target/topDown

      - name: Run Scala topDownWithMemo
        run: sbt "dynamicProgramming/runMain org.combinators.main.GlossaryScalaToDiskMain topDownMemo"

      - name: Validate Scala topDownWithMemo
        run: sbt test
        working-directory: ./target/topDownMemo

      - name: Run Scala bottomUp
        run: sbt "dynamicProgramming/runMain org.combinators.main.GlossaryScalaToDiskMain bottomUp"

      - name: Validate Scala bottomUp
        run: sbt test
        working-directory: ./target/bottomUp
